name: akari
description: "Jouez au Akari en solo ou en duel"
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.2
  tuple: ^2.0.2
  just_audio: ^0.9.36
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.3
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/bulbHome2.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "lib/assets/images/bulbHome2.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/images/bulbHome2.png"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/musics/
    - lib/assets/
